# Generated by Django 4.0.5 on 2023-07-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('groupname', models.CharField(blank=True, max_length=50, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeedepartmenthistory',
            fields=[
                ('employeedepartmenthistoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employeedepartmenthistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeepayhistory',
            fields=[
                ('employeepayhistoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('ratechangedate', models.DateTimeField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('payfrequency', models.SmallIntegerField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employeepayhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('businessentityid', models.IntegerField(primary_key=True, serialize=False)),
                ('persontype', models.CharField(blank=True, max_length=2, null=True)),
                ('namestyle', models.BooleanField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=8, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('emailpromotion', models.IntegerField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shiftid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('businessentityid', models.OneToOneField(db_column='businessentityid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recursos_humanos.person')),
                ('nationalidnumber', models.CharField(blank=True, max_length=15, null=True)),
                ('loginid', models.CharField(blank=True, max_length=256, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=1, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('salariedflag', models.BooleanField(blank=True, null=True)),
                ('vacationhours', models.SmallIntegerField(blank=True, null=True)),
                ('sickleavehours', models.SmallIntegerField(blank=True, null=True)),
                ('currentflag', models.BooleanField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
                ('organizationnode', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
